# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GCSConnector": "00_connectors.gcp.ipynb",
         "BQConnector": "00_connectors.gcp.ipynb"}

modules = ["connectors/gcp.py"]

doc_url = "https://pymousse.github.io/toolkit/"

git_url = "https://github.com/pymousse/toolkit/tree/master/"

def custom_doc_links(name): return None
